const userData = [
  {
    "team": "Argentina",
    "owner": "DJ",
    "played": 0,
    "win": 0,
    "draw": 0,
    "loss": 0,
    "red_cards": 0,
    "yellow_cards": 0,
    "goals_for": 0,
    "goals_against": 0,
    "total_points": 0
  },
  {
    "team": "Belgium",
    "owner": "JR",
    "played": 0,
    "win": 0,
    "draw": 0,
    "loss": 0,
    "red_cards": 0,
    "yellow_cards": 0,
    "goals_for": 0,
    "goals_against": 0,
    "total_points": 0
  },
  {
    "team": "Brazil",
    "owner": "Shane",
    "played": 0,
    "win": 0,
    "draw": 0,
    "loss": 0,
    "red_cards": 0,
    "yellow_cards": 0,
    "goals_for": 0,
    "goals_against": 0,
    "total_points": 0
  },
  {
    "team": "Cameroon",
    "owner": "Jaybee",
    "played": 0,
    "win": 0,
    "draw": 0,
    "loss": 0,
    "red_cards": 0,
    "yellow_cards": 0,
    "goals_for": 0,
    "goals_against": 0,
    "total_points": 0
  },
  {
    "team": "Canada",
    "owner": "Angeli",
    "played": 0,
    "win": 0,
    "draw": 0,
    "loss": 0,
    "red_cards": 0,
    "yellow_cards": 0,
    "goals_for": 0,
    "goals_against": 0,
    "total_points": 0
  },
  {
    "team": "Costa Rica",
    "owner": "Ray",
    "played": 0,
    "win": 0,
    "draw": 0,
    "loss": 0,
    "red_cards": 0,
    "yellow_cards": 0,
    "goals_for": 0,
    "goals_against": 0,
    "total_points": 0
  },
  {
    "team": "Croatia",
    "owner": "Sean",
    "played": 0,
    "win": 0,
    "draw": 0,
    "loss": 0,
    "red_cards": 0,
    "yellow_cards": 0,
    "goals_for": 0,
    "goals_against": 0,
    "total_points": 0
  },
  {
    "team": "Denmark",
    "owner": "Sasi",
    "played": 0,
    "win": 0,
    "draw": 0,
    "loss": 0,
    "red_cards": 0,
    "yellow_cards": 0,
    "goals_for": 0,
    "goals_against": 0,
    "total_points": 0
  },
  {
    "team": "Ecuador",
    "owner": "Jaybee",
    "played": 1,
    "win": 1,
    "draw": 0,
    "loss": 0,
    "red_cards": 0,
    "yellow_cards": 2,
    "goals_for": 2,
    "goals_against": 0,
    "total_points": 12
  },
  {
    "team": "England",
    "owner": "Rein",
    "played": 0,
    "win": 0,
    "draw": 0,
    "loss": 0,
    "red_cards": 0,
    "yellow_cards": 0,
    "goals_for": 0,
    "goals_against": 0,
    "total_points": 0
  },
  {
    "team": "France",
    "owner": "Jaybee",
    "played": 0,
    "win": 0,
    "draw": 0,
    "loss": 0,
    "red_cards": 0,
    "yellow_cards": 0,
    "goals_for": 0,
    "goals_against": 0,
    "total_points": 0
  },
  {
    "team": "Germany",
    "owner": "Sean",
    "played": 0,
    "win": 0,
    "draw": 0,
    "loss": 0,
    "red_cards": 0,
    "yellow_cards": 0,
    "goals_for": 0,
    "goals_against": 0,
    "total_points": 0
  },
  {
    "team": "Ghana",
    "owner": "Shane",
    "played": 0,
    "win": 0,
    "draw": 0,
    "loss": 0,
    "red_cards": 0,
    "yellow_cards": 0,
    "goals_for": 0,
    "goals_against": 0,
    "total_points": 0
  },
  {
    "team": "Iran",
    "owner": "Rein",
    "played": 0,
    "win": 0,
    "draw": 0,
    "loss": 0,
    "red_cards": 0,
    "yellow_cards": 0,
    "goals_for": 0,
    "goals_against": 0,
    "total_points": 0
  },
  {
    "team": "Japan",
    "owner": "JR",
    "played": 0,
    "win": 0,
    "draw": 0,
    "loss": 0,
    "red_cards": 0,
    "yellow_cards": 0,
    "goals_for": 0,
    "goals_against": 0,
    "total_points": 0
  },
  {
    "team": "Korea Republic",
    "owner": "Sasi",
    "played": 0,
    "win": 0,
    "draw": 0,
    "loss": 0,
    "red_cards": 0,
    "yellow_cards": 0,
    "goals_for": 0,
    "goals_against": 0,
    "total_points": 0
  },
  {
    "team": "Mexico",
    "owner": "Rein",
    "played": 0,
    "win": 0,
    "draw": 0,
    "loss": 0,
    "red_cards": 0,
    "yellow_cards": 0,
    "goals_for": 0,
    "goals_against": 0,
    "total_points": 0
  },
  {
    "team": "Morocco",
    "owner": "Emma",
    "played": 0,
    "win": 0,
    "draw": 0,
    "loss": 0,
    "red_cards": 0,
    "yellow_cards": 0,
    "goals_for": 0,
    "goals_against": 0,
    "total_points": 0
  },
  {
    "team": "Netherlands",
    "owner": "Angeli",
    "played": 0,
    "win": 0,
    "draw": 0,
    "loss": 0,
    "red_cards": 0,
    "yellow_cards": 0,
    "goals_for": 0,
    "goals_against": 0,
    "total_points": 0
  },
  {
    "team": "Poland",
    "owner": "Emma",
    "played": 0,
    "win": 0,
    "draw": 0,
    "loss": 0,
    "red_cards": 0,
    "yellow_cards": 0,
    "goals_for": 0,
    "goals_against": 0,
    "total_points": 0
  },
  {
    "team": "Portugal",
    "owner": "Ray",
    "played": 0,
    "win": 0,
    "draw": 0,
    "loss": 0,
    "red_cards": 0,
    "yellow_cards": 0,
    "goals_for": 0,
    "goals_against": 0,
    "total_points": 0
  },
  {
    "team": "Qatar",
    "owner": "DJ",
    "played": 1,
    "win": 0,
    "draw": 0,
    "loss": 1,
    "red_cards": 0,
    "yellow_cards": 4,
    "goals_for": 0,
    "goals_against": 2,
    "total_points": -8
  },
  {
    "team": "Saudia Arabia",
    "owner": "Sean",
    "played": 0,
    "win": 0,
    "draw": 0,
    "loss": 0,
    "red_cards": 0,
    "yellow_cards": 0,
    "goals_for": 0,
    "goals_against": 0,
    "total_points": 0
  },
  {
    "team": "Senegal",
    "owner": "Ray",
    "played": 0,
    "win": 0,
    "draw": 0,
    "loss": 0,
    "red_cards": 0,
    "yellow_cards": 0,
    "goals_for": 0,
    "goals_against": 0,
    "total_points": 0
  },
  {
    "team": "Serbia",
    "owner": "DJ",
    "played": 0,
    "win": 0,
    "draw": 0,
    "loss": 0,
    "red_cards": 0,
    "yellow_cards": 0,
    "goals_for": 0,
    "goals_against": 0,
    "total_points": 0
  },
  {
    "team": "Spain",
    "owner": "Emma",
    "played": 0,
    "win": 0,
    "draw": 0,
    "loss": 0,
    "red_cards": 0,
    "yellow_cards": 0,
    "goals_for": 0,
    "goals_against": 0,
    "total_points": 0
  },
  {
    "team": "Switzerland",
    "owner": "Sasi",
    "played": 0,
    "win": 0,
    "draw": 0,
    "loss": 0,
    "red_cards": 0,
    "yellow_cards": 0,
    "goals_for": 0,
    "goals_against": 0,
    "total_points": 0
  },
  {
    "team": "Uruguay",
    "owner": "Shane",
    "played": 0,
    "win": 0,
    "draw": 0,
    "loss": 0,
    "red_cards": 0,
    "yellow_cards": 0,
    "goals_for": 0,
    "goals_against": 0,
    "total_points": 0
  },
  {
    "team": "USA",
    "owner": "JR",
    "played": 0,
    "win": 0,
    "draw": 0,
    "loss": 0,
    "red_cards": 0,
    "yellow_cards": 0,
    "goals_for": 0,
    "goals_against": 0,
    "total_points": 0
  },
  {
    "team": "Wales",
    "owner": "Angeli",
    "played": 0,
    "win": 0,
    "draw": 0,
    "loss": 0,
    "red_cards": 0,
    "yellow_cards": 0,
    "goals_for": 0,
    "goals_against": 0,
    "total_points": 0
  }
]

export default userData;